version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    
  nginx:
    build: ./requirements/nginx
    image: nginx
    ports:
      - 433:433
    restart: unless-stopped