version: '3.7'

services:
  mariadb:
    build: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    ports:
      - 3306:3306
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - db:/var/lib/mysql
    networks:
      - inceptioNnet
    
  nginx:
    build: ./requirements/nginx
    image: nginx
    container_name: nginx
    ports:
      - 443:443
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inceptioNnet  
    
  wordpress:
    build: ./requirements/wordpress
    image: wordpress
    container_name: wordpress
    ports:
      - 9000:9000
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - wp:/var/www/html
    depends_on:
      - mariadb
      - redis
    networks:
      - inceptioNnet

  redis:
    build: ./requirements/bonus/redis
    image: redis
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - inceptioNnet
      

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/iomayr/data/mysql
  wp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /Users/iomayr/data/wordpress
networks:
  inceptioNnet:
    driver: bridge
