FROM debian:buster

RUN apt update -y && \
    apt install mariadb-server -y

EXPOSE 3306

COPY ./tools/initial_db.sql /etc/initial_db.sql
COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d

RUN  service mysql start && mysql -u root < /etc/initial_db.sql  && rm -f /var/www/initial_db.sql;

CMD [ "mysqld" ]
