FROM debian:buster

RUN apt update -y && \
    apt install mariadb-server -y

EXPOSE 3306

COPY ./conf/initial_db.sql /tmp/initial_db.sql
COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d

RUN  service mysql start && mysql -u root < /tmp/initial_db.sql;

CMD [ "mysqld" ]
