FROM debian:buster

RUN apt update -y;  apt upgrade -y;\
    apt install apache2 wget php libapache2-mod-php php-mysql -y;\
    cd /var/www/html; rm -rf *;\
    wget https://www.adminer.org/latest.php -O /var/www/html/index.php;\
    sed -i 's/80/8080/g' /etc/apache2/ports.conf;\
    echo "ServerName localhost" >> /etc/apache2/apache2.conf;\
    service apache2 restart

CMD ["apachectl", "-D", "FOREGROUND"]