FROM debian:buster

RUN apt update -y;  apt upgrade -y;
RUN apt install apache2 wget php libapache2-mod-php php-mysql -y;
RUN cd /var/www/html; rm -rf *;
RUN wget https://www.adminer.org/latest.php -O /var/www/html/index.php
RUN sed -i 's/80/8080/g' /etc/apache2/ports.conf;
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN service apache2 restart

CMD ["apachectl", "-D", "FOREGROUND"]