FROM debian:buster

EXPOSE 9000

RUN apt-get update && \
    apt-get install -y php7.3-fpm php7.3-mysql sendmail && \
    apt-get install -y curl

COPY ./conf/script.sh /

RUN curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
RUN chmod +x wp-cli.phar
RUN mv wp-cli.phar /usr/local/bin/wp

COPY /conf/www.conf /etc/php/7.3/fpm/pool.d/
RUN chmod +x script.sh

CMD [ "./script.sh" ]