CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER 'iomayr'@localhost IDENTIFIED BY 'user123321';
GRANT ALL PRIVILEGES ON 'iomayr'@localhost IDENTIFIED BY 'user123321';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123321';