CREATE DATABASE IF NOT EXISTS wordpress;
CREATE USER IF NOT EXISTS 'iomayr'@localhost;
GRANT ALL PRIVILEGES ON wordpress.* to 'iomayr'@'%' IDENTIFIED BY 'user123321';
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root123321';
FLUSH PRIVILEGES;